[build]
command = """
curl -fsSL https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.19.0-stable.tar.xz | tar -xJf - &&
export PATH=$PWD/flutter/bin:$PATH &&
flutter doctor &&
flutter clean &&
flutter pub get &&
flutter build web
"""
publish = "build/web"