[build]
command = "apt-get update && apt-get install -y coreutils && curl -sL https://storage.googleapis.com/download.flutter.io/flutter_linux_2.10.5-stable.tar.xz | tar -xJf - -C /opt && export PATH=/opt/flutter/bin:$PATH && flutter doctor && flutter build web"
publish = "build/web"

[build.environment]
PATH = "/opt/flutter/bin:$PATH"