import '../../product/repository/product_data.dart';
import '../model/order_detail_model.dart';
import '../model/order_model.dart';

List<OrderModel> demoOrders = [
  OrderModel(
    id: "ORD001",
    customerName: "Nguyễn Văn A",
    orderStatus: "completed",
    totalPayment: 175000,
    paymentStatus: "paid",
    paymentEmployee: "Lê Thị B",
    orderEmployee: "Trần Văn C",
    orderDetails: [
      OrderDetailModel(
        product: demoProducts[0],
        quantity: 2,
        totalPrice: 70000,
      ),
      OrderDetailModel(
        product: demoProducts[1],
        quantity: 1,
        totalPrice: 40000,
      ),
      OrderDetailModel(
        product: demoProducts[2],
        quantity: 1,
        totalPrice: 45000,
      ),
    ],
    createdAt: DateTime.now().subtract(Duration(days: 5)),
    updatedAt: DateTime.now(),
  ),
  OrderModel(
    id: "ORD002",
    customerName: "Trần Thị B",
    orderStatus: "pending",
    totalPayment: 120000,
    paymentStatus: "unpaid",
    paymentEmployee: "Đặng Văn E",
    orderEmployee: "Nguyễn Thị F",
    orderDetails: [
      OrderDetailModel(
        product: demoProducts[3],
        quantity: 2,
        totalPrice: 120000,
      ),
    ],
    createdAt: DateTime.now().subtract(Duration(days: 2)),
    updatedAt: DateTime.now(),
  ),
  OrderModel(
    id: "ORD003",
    customerName: "Hoàng Văn C",
    orderStatus: "canceled",
    totalPayment: 80000,
    paymentStatus: "unpaid",
    paymentEmployee: "Lê Thị B",
    orderEmployee: "Trần Văn C",
    orderDetails: [
      OrderDetailModel(
        product: demoProducts[4],
        quantity: 1,
        totalPrice: 80000,
      ),
    ],
    createdAt: DateTime.now().subtract(Duration(days: 7)),
    updatedAt: DateTime.now(),
  ),
  OrderModel(
    id: "ORD004",
    customerName: "Lê Thị D",
    orderStatus: "completed",
    totalPayment: 250000,
    paymentStatus: "paid",
    paymentEmployee: "Hoàng Minh E",
    orderEmployee: "Nguyễn Văn F",
    orderDetails: [
      OrderDetailModel(
        product: demoProducts[5],
        quantity: 2,
        totalPrice: 140000,
      ),
      OrderDetailModel(
        product: demoProducts[6],
        quantity: 2,
        totalPrice: 110000,
      ),
    ],
    createdAt: DateTime.now().subtract(Duration(days: 1)),
    updatedAt: DateTime.now(),
  ),
  OrderModel(
    id: "ORD005",
    customerName: "Đặng Thị E",
    orderStatus: "pending",
    totalPayment: 65000,
    paymentStatus: "unpaid",
    paymentEmployee: "Nguyễn Văn Y",
    orderEmployee: "Trần Thị X",
    orderDetails: [
      OrderDetailModel(
        product: demoProducts[3],
        quantity: 2,
        totalPrice: 50000,
      ),
      OrderDetailModel(
        product: demoProducts[2],
        quantity: 1,
        totalPrice: 15000,
      ),
    ],
    createdAt: DateTime.now().subtract(Duration(hours: 12)),
    updatedAt: DateTime.now(),
  ),
  OrderModel(
    id: "ORD006",
    customerName: "Nguyễn Minh G",
    orderStatus: "completed",
    totalPayment: 105000,
    paymentStatus: "paid",
    paymentEmployee: "Hoàng Anh H",
    orderEmployee: "Nguyễn Văn I",
    orderDetails: [
      OrderDetailModel(
        product: demoProducts[1],
        quantity: 1,
        totalPrice: 50000,
      ),
      OrderDetailModel(
        product: demoProducts[0],
        quantity: 1,
        totalPrice: 55000,
      ),
    ],
    createdAt: DateTime.now().subtract(Duration(days: 3)),
    updatedAt: DateTime.now(),
  ),
  OrderModel(
    id: "ORD007",
    customerName: "Trần Văn H",
    orderStatus: "canceled",
    totalPayment: 180000,
    paymentStatus: "unpaid",
    paymentEmployee: "Đặng Văn J",
    orderEmployee: "Nguyễn Thị K",
    orderDetails: [
      OrderDetailModel(
        product: demoProducts[4],
        quantity: 2,
        totalPrice: 180000,
      ),
    ],
    createdAt: DateTime.now().subtract(Duration(days: 6)),
    updatedAt: DateTime.now(),
  ),
  OrderModel(
    id: "ORD008",
    customerName: "Lương Thị L",
    orderStatus: "completed",
    totalPayment: 220000,
    paymentStatus: "paid",
    paymentEmployee: "Hoàng Anh M",
    orderEmployee: "Nguyễn Văn N",
    orderDetails: [
      OrderDetailModel(
        product: demoProducts[5],
        quantity: 4,
        totalPrice: 220000,
      ),
    ],
    createdAt: DateTime.now().subtract(Duration(days: 8)),
    updatedAt: DateTime.now(),
  ),
  OrderModel(
    id: "ORD009",
    customerName: "Phạm Văn O",
    orderStatus: "pending",
    totalPayment: 75000,
    paymentStatus: "unpaid",
    paymentEmployee: "Nguyễn Văn P",
    orderEmployee: "Trần Thị Q",
    orderDetails: [
      OrderDetailModel(
        product: demoProducts[6],
        quantity: 3,
        totalPrice: 75000,
      ),
    ],
    createdAt: DateTime.now().subtract(Duration(days: 2)),
    updatedAt: DateTime.now(),
  ),
  OrderModel(
    id: "ORD010",
    customerName: "Đỗ Văn R",
    orderStatus: "completed",
    totalPayment: 200000,
    paymentStatus: "paid",
    paymentEmployee: "Hoàng Anh S",
    orderEmployee: "Nguyễn Văn T",
    orderDetails: [
      OrderDetailModel(
        product: demoProducts[7],
        quantity: 2,
        totalPrice: 200000,
      ),
    ],
    createdAt: DateTime.now().subtract(Duration(days: 4)),
    updatedAt: DateTime.now(),
  ),
  OrderModel(
    id: "ORD011",
    customerName: "Nguyễn Hữu A",
    orderStatus: "pending",
    totalPayment: 135000,
    paymentStatus: "unpaid",
    paymentEmployee: "Trần Thị B",
    orderEmployee: "Lê Văn C",
    orderDetails: [
      OrderDetailModel(
        product: demoProducts[2],
        quantity: 3,
        totalPrice: 135000,
      ),
    ],
    createdAt: DateTime.now().subtract(Duration(days: 3)),
    updatedAt: DateTime.now(),
  ),
  OrderModel(
    id: "ORD012",
    customerName: "Trần Văn D",
    orderStatus: "completed",
    totalPayment: 180000,
    paymentStatus: "paid",
    paymentEmployee: "Nguyễn Minh E",
    orderEmployee: "Đặng Thị F",
    orderDetails: [
      OrderDetailModel(
        product: demoProducts[4],
        quantity: 2,
        totalPrice: 180000,
      ),
    ],
    createdAt: DateTime.now().subtract(Duration(days: 1)),
    updatedAt: DateTime.now(),
  ),
  OrderModel(
    id: "ORD013",
    customerName: "Lê Thị G",
    orderStatus: "canceled",
    totalPayment: 90000,
    paymentStatus: "unpaid",
    paymentEmployee: "Hoàng Văn H",
    orderEmployee: "Phạm Thị I",
    orderDetails: [
      OrderDetailModel(
        product: demoProducts[1],
        quantity: 2,
        totalPrice: 90000,
      ),
    ],
    createdAt: DateTime.now().subtract(Duration(days: 5)),
    updatedAt: DateTime.now(),
  ),
  OrderModel(
    id: "ORD014",
    customerName: "Đặng Văn J",
    orderStatus: "pending",
    totalPayment: 50000,
    paymentStatus: "unpaid",
    paymentEmployee: "Nguyễn Thị K",
    orderEmployee: "Trần Minh L",
    orderDetails: [
      OrderDetailModel(
        product: demoProducts[0],
        quantity: 1,
        totalPrice: 50000,
      ),
    ],
    createdAt: DateTime.now().subtract(Duration(hours: 10)),
    updatedAt: DateTime.now(),
  ),
  OrderModel(
    id: "ORD015",
    customerName: "Phạm Hữu M",
    orderStatus: "completed",
    totalPayment: 250000,
    paymentStatus: "paid",
    paymentEmployee: "Lê Văn N",
    orderEmployee: "Đặng Minh O",
    orderDetails: [
      OrderDetailModel(
        product: demoProducts[3],
        quantity: 5,
        totalPrice: 250000,
      ),
    ],
    createdAt: DateTime.now().subtract(Duration(days: 2)),
    updatedAt: DateTime.now(),
  ),
  OrderModel(
    id: "ORD016",
    customerName: "Nguyễn Thị P",
    orderStatus: "completed",
    totalPayment: 75000,
    paymentStatus: "paid",
    paymentEmployee: "Trần Văn Q",
    orderEmployee: "Lê Thị R",
    orderDetails: [
      OrderDetailModel(
        product: demoProducts[6],
        quantity: 3,
        totalPrice: 75000,
      ),
    ],
    createdAt: DateTime.now().subtract(Duration(days: 6)),
    updatedAt: DateTime.now(),
  ),
  OrderModel(
    id: "ORD017",
    customerName: "Đỗ Văn S",
    orderStatus: "pending",
    totalPayment: 110000,
    paymentStatus: "unpaid",
    paymentEmployee: "Hoàng Minh T",
    orderEmployee: "Nguyễn Văn U",
    orderDetails: [
      OrderDetailModel(
        product: demoProducts[5],
        quantity: 2,
        totalPrice: 110000,
      ),
    ],
    createdAt: DateTime.now().subtract(Duration(days: 3)),
    updatedAt: DateTime.now(),
  ),
  OrderModel(
    id: "ORD018",
    customerName: "Trần Hữu V",
    orderStatus: "canceled",
    totalPayment: 60000,
    paymentStatus: "unpaid",
    paymentEmployee: "Đặng Thị W",
    orderEmployee: "Phạm Văn X",
    orderDetails: [
      OrderDetailModel(
        product: demoProducts[7],
        quantity: 1,
        totalPrice: 60000,
      ),
    ],
    createdAt: DateTime.now().subtract(Duration(days: 7)),
    updatedAt: DateTime.now(),
  ),
  OrderModel(
    id: "ORD019",
    customerName: "Lương Văn Y",
    orderStatus: "completed",
    totalPayment: 190000,
    paymentStatus: "paid",
    paymentEmployee: "Nguyễn Văn Z",
    orderEmployee: "Hoàng Thị A",
    orderDetails: [
      OrderDetailModel(
        product: demoProducts[2],
        quantity: 4,
        totalPrice: 190000,
      ),
    ],
    createdAt: DateTime.now().subtract(Duration(days: 4)),
    updatedAt: DateTime.now(),
  ),
  OrderModel(
    id: "ORD020",
    customerName: "Nguyễn Minh B",
    orderStatus: "pending",
    totalPayment: 85000,
    paymentStatus: "unpaid",
    paymentEmployee: "Trần Thị C",
    orderEmployee: "Lê Văn D",
    orderDetails: [
      OrderDetailModel(
        product: demoProducts[0],
        quantity: 2,
        totalPrice: 85000,
      ),
    ],
    createdAt: DateTime.now().subtract(Duration(days: 1)),
    updatedAt: DateTime.now(),
  ),
];
